### ISSUE TITLE
andWhere method enhancement

### ISSUE THREAD

**Issue by kuhma** [elie29/oci-driver#33]
In case of a dynamic build, `where `and `andWhere `may be in a random sequence as follow:
```PHP
Select::start()
    ->column('count(*)')
    ->from('table t')
    ->andWhere('t.column1 = condition')
    ->where('t.column2 = condition')
```

Build method should address this issue.

I suggest to make `where` an alias of `andWhere`.

**Comment by elie29** [comment]
done 👍
