### ISSUE TITLE
accept a SELECT type in Join

### ISSUE THREAD

**Issue by habelmlouk** [elie29/oci-driver#47]
Hello,

I suggest add the type SELECT in Join like from
for exemple
select sal.NOM, sal.PRENOM, sal.MATRICULE
from T_V5_KRH_SALARIE sal
join T_V5_KRH_PROFIL_USER usr on sal.MATRICULE = usr.MATRICULE
join (
    select COLLABORATEUR from V_V5_KRH_DESIGN_XP_PAIE where ACTEUR = :MATRICULE_EXPERT
    union
    select COLLABORATEUR from V_V5_KRH_DESIGN_XP_FORM where ACTEUR = :MATRICULE_EXPERT
    union
    select COLLABORATEUR from V_V5_KRH_DESIGN_XP_ENTR where ACTEUR = :MATRICULE_EXPERT
) perim on perim.COLLABORATEUR = sal.MATRICULE;

with query builder

        $select = Select::start()
            ->columns(self::COLS_SAL, 'sal')
            ->column(self::COL_USER, 'usr')
            ->from('T_V5_KRH_SALARIE', 'sal')
            ->join(MySelect, 'usr', 'usr.MATRICULE = sal.MATRICULE');

**Comment by elie29** [comment]
The change should be:

```php
public function join(string $table, string $alias, string $condition): self
{
     return $this->forJoin('INNER JOIN', $table, $alias, $condition);
}

if ($tabe instanceOf Select) {
  $table = '(', $table.build . ')';
}

@habelmlouk  could do the change?

**Comment by habelmlouk** [comment]
@elie29 with pleasure
